import { describe, it, expect, vi, beforeEach } from "vitest";

// Mock Supabase client before importing db module
vi.mock("@/integrations/supabase/client", () => ({
  supabase: {
    from: vi.fn(),
    auth: { getSession: vi.fn(), onAuthStateChange: vi.fn() },
  },
}));

import { getRedirectUrl } from "@/lib/db";

// ─── getRedirectUrl ───────────────────────────────────────────────────────────

describe("getRedirectUrl", () => {
  beforeEach(() => {
    vi.stubEnv("VITE_SUPABASE_URL", "https://test-project.supabase.co");
  });

  it("returns correct redirect URL for a given short code", () => {
    const url = getRedirectUrl("ABC123");
    expect(url).toBe("https://test-project.supabase.co/functions/v1/redirect/ABC123");
  });

  it("includes the short code verbatim", () => {
    const url = getRedirectUrl("XYZ999");
    expect(url).toContain("XYZ999");
  });

  it("always ends with the short code", () => {
    const code = "QR1234";
    const url = getRedirectUrl(code);
    expect(url.endsWith(code)).toBe(true);
  });
});

// ─── Short code format ────────────────────────────────────────────────────────
// Tests the expected format generated by generateShortCode (6 uppercase alphanumeric)

describe("short code format contract", () => {
  const SHORT_CODE_PATTERN = /^[A-Z0-9]{6}$/;

  it("validates the expected 6-char uppercase alphanumeric pattern", () => {
    const validCodes = ["ABC123", "ZZZZZZ", "000000", "A1B2C3"];
    validCodes.forEach((code) => {
      expect(SHORT_CODE_PATTERN.test(code)).toBe(true);
    });
  });

  it("rejects lowercase codes", () => {
    expect(SHORT_CODE_PATTERN.test("abc123")).toBe(false);
  });

  it("rejects codes not exactly 6 chars", () => {
    expect(SHORT_CODE_PATTERN.test("AB12")).toBe(false);
    expect(SHORT_CODE_PATTERN.test("ABCDEFG")).toBe(false);
  });

  it("rejects codes with special characters", () => {
    expect(SHORT_CODE_PATTERN.test("AB-123")).toBe(false);
    expect(SHORT_CODE_PATTERN.test("AB 123")).toBe(false);
  });
});
